---
language: cpp

os:
  - linux

dist: focal
sudo: required

compiler:
  - gcc

before_install:
  sudo apt-get -y install libgtest-dev

install:
  - g++ --version
  - cmake --version

before_script:
  - mkdir build
  - cmake -DCMAKE_BUILD_TYPE=Release -S . -B build

script:
  - cmake --build build --target test_fndrd1d1 -- -j 4
  - build/test_fndrd1d1
  - cmake --build build --target test_0xPwner -- -j 4
  - build/test_0xPwner
